# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MangoPlateClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangoPlateClone

pod 'KakaoSDKUser'
pod 'KakaoSDKAuth'
pod 'KakaoSDKCommon'
pod 'Alamofire'
pod 'Tabman', '~> 2.11'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SwiftyJSON'

end
